In [636]:
import pandas as pd
import numpy as np

In [637]:
df = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [638]:
df.info()
print('_'*40)
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB
________________________________________
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
PassengerId    418 non-null int64
Pclass         418 non-null int64
Name           418 non-null object
Sex            418 non-null object
Age            332 non-null float64
SibSp          418 non-null int64
Parch          418 non-null int64
Ticket         418 non-null

In [639]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [640]:
df.describe(include=['O'])

Name   Sex    Ticket        Cabin Embarked
count                       891   891       891          204      889
unique                      891     2       681          147        3
top     Renouf, Mr. Peter Henry  male  CA. 2343  C23 C25 C27        S
freq                          1   577         7            4      644

In [641]:
df[['Pclass', 'Survived']].groupby(['Pclass'], as_index=False).mean().sort_values(by='Survived', ascending=False)

Pclass  Survived
0       1  0.629630
1       2  0.472826
2       3  0.242363

In [642]:
df[['Sex', 'Survived']].groupby(['Sex'], as_index=False).mean().sort_values(by="Survived", ascending=False)

Sex  Survived
0  female  0.742038
1    male  0.188908

In [643]:
df[['SibSp', 'Survived']].groupby(['SibSp'], as_index=False).mean().sort_values(by='Survived', ascending = False)

SibSp  Survived
1      1  0.535885
2      2  0.464286
0      0  0.345395
3      3  0.250000
4      4  0.166667
5      5  0.000000
6      8  0.000000

In [644]:
df[['Parch', 'Survived']].groupby(['Parch'], as_index=False).mean().sort_values(by='Survived', ascending=False)

Parch  Survived
3      3  0.600000
1      1  0.550847
2      2  0.500000
0      0  0.343658
5      5  0.200000
4      4  0.000000
6      6  0.000000

In [645]:
df[['Embarked', 'Survived']].groupby(['Embarked'], as_index=False).mean().sort_values(by='Survived', ascending=False)

Embarked  Survived
0        C  0.553571
1        Q  0.389610
2        S  0.336957

In [646]:
df["Sex"][df["Sex"] == "male"] = 0
df["Sex"][df["Sex"] == "female"] = 1

df["Embarked"].fillna('U', inplace=True)

df["Embarked"][df["Embarked"] == "S"] = 0
df["Embarked"][df["Embarked"] == "C"] = 1
df["Embarked"][df["Embarked"] == "Q"] = 2
df["Embarked"][df["Embarked"] == "U"] = 3

df["Age"].fillna(df["Age"].median(), inplace=True)

df = df.drop(['Ticket','Cabin'], axis=1)
# Remove NaN values
df = df.dropna() 

df_test["Sex"][df_test["Sex"] == "male"] = 0
df_test["Sex"][df_test["Sex"] == "female"] = 1

df_test["Embarked"].fillna('U', inplace=True)
df_test["Embarked"][df_test["Embarked"] == "S"] = 0
df_test["Embarked"][df_test["Embarked"] == "C"] = 1
df_test["Embarked"][df_test["Embarked"] == "Q"] = 2
df_test["Embarked"][df_test["Embarked"] == "U"] = 3


df_test["Age"].fillna(df_test["Age"].median(), inplace=True)
df_test["Fare"].fillna(df_test["Fare"].median(), inplace=True)

train = df.copy()
train["family_size"] = df['SibSp'] + df['Parch'] + 1
test = df_test.copy()
test["family_size"] = df_test['SibSp'] + df_test['Parch'] + 1

C:\Users\Shlok Khandelwal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\Shlok Khandelwal\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\Shlok Khandelwal\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\Shlok Khandelwal\Anaconda3\lib\site-packages\ipykernel_l

In [647]:
target = df['Survived'].values
features = train[["Pclass", "Age", "Sex", "Fare", "family_size", "Embarked"]].values
test_features = test[["Pclass", "Age", "Sex", "Fare", "family_size", "Embarked"]].values

In [648]:
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X = features
Y = target
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = .25, random_state = 7)


In [649]:

model1 = XGBClassifier(max_depth=4)
model1.fit(X_train, Y_train)

y_pred = model1.predict(X_test)
print("XGB boost:")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

XGB boost:
0.798206278027
             precision    recall  f1-score   support

          0       0.79      0.90      0.84       135
          1       0.81      0.64      0.71        88

avg / total       0.80      0.80      0.79       223

[[122  13]
 [ 32  56]]


In [650]:
from sklearn import datasets
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
# fit a logistic regression model to the data
model = LogisticRegression()
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)
# summarize the fit of the model
print("Logistic Regression: ")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

Logistic Regression: 
0.766816143498
             precision    recall  f1-score   support

          0       0.78      0.85      0.82       135
          1       0.74      0.64      0.68        88

avg / total       0.76      0.77      0.76       223

[[115  20]
 [ 32  56]]


In [651]:
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
model2 = GaussianNB()
model2.fit(X_train, Y_train)
# make predictions
y_pred = model2.predict(X_test)
# summarize the fit of the model
print("Gaussian Naive Bayes:")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

Gaussian Naive Bayes:
0.77130044843
             precision    recall  f1-score   support

          0       0.79      0.85      0.82       135
          1       0.74      0.65      0.69        88

avg / total       0.77      0.77      0.77       223

[[115  20]
 [ 31  57]]


In [652]:
from sklearn import datasets
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier()
model.fit(X_train, Y_train)
# make predictions
y_pred = model.predict(X_test)
# summarize the fit of the model
print("k-Nearest Neighbor: ")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

k-Nearest Neighbor: 
0.708520179372
             precision    recall  f1-score   support

          0       0.73      0.82      0.77       135
          1       0.66      0.53      0.59        88

avg / total       0.70      0.71      0.70       223

[[111  24]
 [ 41  47]]


In [653]:
from sklearn import datasets
from sklearn import metrics
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, Y_train)

# make predictions
y_pred = model.predict(X_test)
# summarize the fit of the model
print("Support Vector Machine: ")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

Support Vector Machine: 
0.668161434978
             precision    recall  f1-score   support

          0       0.68      0.86      0.76       135
          1       0.63      0.38      0.47        88

avg / total       0.66      0.67      0.65       223

[[116  19]
 [ 55  33]]


In [654]:
from sklearn import datasets
from sklearn import metrics
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
model.fit(X_train, Y_train)
# make predictions
y_pred = model.predict(X_test)
# summarize the fit of the model
print("Classification and Regression Trees")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

Classification and Regression Trees
0.726457399103
             precision    recall  f1-score   support

          0       0.77      0.79      0.78       135
          1       0.66      0.64      0.65        88

avg / total       0.72      0.73      0.73       223

[[106  29]
 [ 32  56]]


In [655]:
from sklearn.ensemble import AdaBoostClassifier
model = AdaBoostClassifier()
model.fit(X_train, Y_train)
y_pred = model.predict(X_test)
print("Ada boost:")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

Ada boost:
0.7533632287
             precision    recall  f1-score   support

          0       0.77      0.84      0.80       135
          1       0.71      0.62      0.67        88

avg / total       0.75      0.75      0.75       223

[[113  22]
 [ 33  55]]


In [656]:
from sklearn.ensemble import RandomForestClassifier
model3 = RandomForestClassifier()
model3.fit(X_train, Y_train)
y_pred = model3.predict(X_test)
print("Random Forest Tree:")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

Random Forest Tree:
0.77130044843
             precision    recall  f1-score   support

          0       0.80      0.82      0.81       135
          1       0.72      0.69      0.71        88

avg / total       0.77      0.77      0.77       223

[[111  24]
 [ 27  61]]


In [657]:
from sklearn.ensemble import VotingClassifier
eclf1 = VotingClassifier(estimators=[('xgb', model1), ('gnb', model2), ('rf', model3)], voting="soft")
eclf1.fit(X_train, Y_train)
y_pred = eclf1.predict(X_test)
print("Ensemble")
print(metrics.accuracy_score(Y_test, y_pred))
print(metrics.classification_report(Y_test, y_pred))
print(metrics.confusion_matrix(Y_test, y_pred))

Ensemble
0.775784753363
             precision    recall  f1-score   support

          0       0.78      0.87      0.83       135
          1       0.76      0.62      0.69        88

avg / total       0.77      0.78      0.77       223

[[118  17]
 [ 33  55]]


In [658]:
model1 = XGBClassifier(max_depth=4)
model2 = RandomForestClassifier()
model3 = GaussianNB()
model = VotingClassifier(estimators=[('xgb', model1), ('gnb', model2), ('rf', model3)], voting="soft")
model.fit(features, target)

predictions = model.predict(test_features)
PassengerId = np.array(df_test["PassengerId"]).astype(int)
my_solution = pd.DataFrame(predictions, PassengerId, columns=["Survived"])

my_solution.to_csv("my_solution.csv", index_label = ["PassengerId"])